name: pull request

on:
  pull_request:
    paths:
      - 'packages/**/*'
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  call-workflow:
    uses: ./.github/workflows/reusable.yml
