name: jopau-react/utils

on:
  push:
    paths:
      - 'packages/utils/**'
      - '.github/workflows/utils.yml'
    branches: [main]

  pull_request:
    paths:
      - 'packages/utils/**'
      - '.github/workflows/utils.yml'
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  call-workflow:
    uses: ./.github/workflows/reusable.yml
    with:
      package: utils
